name: devcon-gnr
services:
  devcon-gnr:
    image: hiro345g/devcon-gnr:1.0
    container_name: devcon-gnr
    hostname: devcon-gnr
    init: true
    tty: true
    user: node
    working_dir: /home/node/workspace
    networks:
      devnode-net:
    volumes:
      - workspace-data:/home/node/workspace
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - type: bind
        source: ${SHARE_DIR:-./workspace_share}
        target: /share
    environment:
      ENV LANGUAGE: ja_JP.UTF-8
      ENV LANG: ja_JP.UTF-8
      ENV LC_ALL: ja_JP.UTF-8
      EDITOR: code
      NPM_CONFIG_USERCONFIG: /home/node/.npmrc

volumes:
  workspace-data:
    name: devcon-gnr-node-workspace-data
  vscode-server-extensions:
    name: devcon-gnr-vscode-server-extensions

networks:
  devnode-net:
    name: devcon-gnr-net
